version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: project_management_db
    environment:
      POSTGRES_DB: project_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project_management_network

  redis:
    image: redis:7-alpine
    container_name: project_management_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - project_management_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: project_management_backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/project_management
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    networks:
      - project_management_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: project_management_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - project_management_network
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  project_management_network:
    driver: bridge 